### Array manipulation


In [1]:
import numpy as np

In [3]:
arr = [1,2,3,3,54,6,7]

In [4]:
np.random.randint(arr)

array([ 0,  1,  1,  2, 23,  5,  5])

In [6]:
arr2 = np.random.randint(1,10, (2,5))

In [7]:
arr2

array([[2, 9, 4, 7, 3],
       [8, 6, 5, 6, 6]])

In [8]:
arr2.reshape(5,2)

array([[2, 9],
       [4, 7],
       [3, 8],
       [6, 5],
       [6, 6]])

In [9]:
arr2 .reshape(1,10)

array([[2, 9, 4, 7, 3, 8, 6, 5, 6, 6]])

In [10]:
arr2.reshape(10,1)

array([[2],
       [9],
       [4],
       [7],
       [3],
       [8],
       [6],
       [5],
       [6],
       [6]])

In [12]:
# capital T ka mtlb old array me change kar deta hai

arr2.T

array([[2, 8],
       [9, 6],
       [4, 5],
       [7, 6],
       [3, 6]])

In [14]:
# flatten function me 2D se one 1D me badal jata hai

arr2.flatten()

array([2, 9, 4, 7, 3, 8, 6, 5, 6, 6])

In [15]:
# Expand function 1D se 2D me badal deta hai

arr5 = np.array([1,3,54,6,7,8])

In [16]:
arr5.ndim

1

In [18]:
np.expand_dims(arr5 , axis=1)

array([[ 1],
       [ 3],
       [54],
       [ 6],
       [ 7],
       [ 8]])

In [19]:
np.expand_dims(arr5 , axis=0)

array([[ 1,  3, 54,  6,  7,  8]])

In [21]:
data = np.array([[2],[3],[4],[43],[5],[76]])

In [22]:
data

array([[ 2],
       [ 3],
       [ 4],
       [43],
       [ 5],
       [76]])

In [23]:
# squeeze function 2d array ko (or) ek array ke andar alag alag kostak wale data ko ek 1D arrray (or) ek hi kostak me rakh deta hai

np.squeeze(data)

array([ 2,  3,  4, 43,  5, 76])

In [24]:
# repeat function me data utni baar repeat ho jata hai

arr

[1, 2, 3, 3, 54, 6, 7]

In [25]:
np.repeat(arr , 5)

array([ 1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3, 54, 54, 54, 54, 54,  6,  6,  6,  6,  6,  7,  7,  7,  7,
        7])

In [27]:
# roll function me jis column me sankhya hai aur shift me ank dalte hain dono ko add karke jitna aata hai us column me us sankhya ko rakh deta hai

np.roll(arr,shift=2)

array([ 6,  7,  1,  2,  3,  3, 54])

In [28]:
np.diag(arr)

array([[ 1,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0, 54,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  7]])

### Binary oprations

In [36]:
arr

[1, 2, 3, 3, 54, 6, 7]

In [37]:
arr2

array([[2, 9, 4, 7, 3],
       [8, 6, 5, 6, 6]])

In [42]:
arr3 = np.random.randint(1,8,(2,5))

In [43]:
arr3

array([[2, 4, 4, 7, 1],
       [1, 7, 1, 2, 7]])

In [44]:
arr2 + arr3

array([[ 4, 13,  8, 14,  4],
       [ 9, 13,  6,  8, 13]])

In [45]:
arr2 - arr3

array([[ 0,  5,  0,  0,  2],
       [ 7, -1,  4,  4, -1]])

In [46]:
arr2 * arr3

array([[ 4, 36, 16, 49,  3],
       [ 8, 42,  5, 12, 42]])

In [47]:
arr2 / arr3

array([[1.        , 2.25      , 1.        , 1.        , 3.        ],
       [8.        , 0.85714286, 5.        , 3.        , 0.85714286]])

In [48]:
arr2 % arr3

array([[0, 1, 0, 0, 0],
       [0, 6, 0, 0, 6]])

In [49]:
arr2 ** arr3

array([[     4,   6561,    256, 823543,      3],
       [     8, 279936,      5,     36, 279936]])

In [50]:
arr2 & arr3

array([[2, 0, 4, 7, 1],
       [0, 6, 1, 2, 6]])

In [52]:
~arr2

array([[ -3, -10,  -5,  -8,  -4],
       [ -9,  -7,  -6,  -7,  -7]])

In [53]:
~arr3

array([[-3, -5, -5, -8, -2],
       [-2, -8, -2, -3, -8]])

In [57]:
arr2 | arr3

array([[ 2, 13,  4,  7,  3],
       [ 9,  7,  5,  6,  7]])

In [59]:
arr2 > arr3

array([[False,  True, False, False,  True],
       [ True, False,  True,  True, False]])

In [60]:
arr2 < arr3

array([[False, False, False, False, False],
       [False,  True, False, False,  True]])

### String function

In [63]:
arr = np.array(["priya","rajni"])

In [64]:
arr

array(['priya', 'rajni'], dtype='<U5')

In [65]:
np.char.upper(arr)

array(['PRIYA', 'RAJNI'], dtype='<U5')

In [67]:
np.char.title(arr)

array(['Priya', 'Rajni'], dtype='<U5')

In [68]:
np.char.capitalize(arr)

array(['Priya', 'Rajni'], dtype='<U5')

### mathmetical function

In [69]:
arr2

array([[2, 4, 4, 7, 1],
       [1, 7, 1, 2, 7]])

In [70]:
np.tan(arr2)

array([[-2.18503986,  1.15782128,  1.15782128,  0.87144798,  1.55740772],
       [ 1.55740772,  0.87144798,  1.55740772, -2.18503986,  0.87144798]])

In [71]:
np.sin(arr2)

array([[ 0.90929743, -0.7568025 , -0.7568025 ,  0.6569866 ,  0.84147098],
       [ 0.84147098,  0.6569866 ,  0.84147098,  0.90929743,  0.6569866 ]])

In [72]:
np.cos(arr2)

array([[-0.41614684, -0.65364362, -0.65364362,  0.75390225,  0.54030231],
       [ 0.54030231,  0.75390225,  0.54030231, -0.41614684,  0.75390225]])

In [73]:
np.tanh(arr2)

array([[0.96402758, 0.9993293 , 0.9993293 , 0.99999834, 0.76159416],
       [0.76159416, 0.99999834, 0.76159416, 0.96402758, 0.99999834]])

In [76]:
np.log(arr2)

array([[0.69314718, 1.38629436, 1.38629436, 1.94591015, 0.        ],
       [0.        , 1.94591015, 0.        , 0.69314718, 1.94591015]])

In [77]:
np.log10(arr2)

array([[0.30103   , 0.60205999, 0.60205999, 0.84509804, 0.        ],
       [0.        , 0.84509804, 0.        , 0.30103   , 0.84509804]])

In [78]:
np.exp(arr2)

array([[   7.3890561 ,   54.59815003,   54.59815003, 1096.63315843,
           2.71828183],
       [   2.71828183, 1096.63315843,    2.71828183,    7.3890561 ,
        1096.63315843]])

In [79]:
np.sqrt(arr2)

array([[1.41421356, 2.        , 2.        , 2.64575131, 1.        ],
       [1.        , 2.64575131, 1.        , 1.41421356, 2.64575131]])

In [81]:
np.power(arr2 ,2)

array([[ 4, 16, 16, 49,  1],
       [ 1, 49,  1,  4, 49]], dtype=int32)

In [82]:
np.mean(arr2)

3.6

In [83]:
np.median(arr2)

3.0

In [85]:
np.std(arr2)

2.4576411454889016

In [86]:
np.var(arr2)

6.040000000000001

In [87]:
np.min(arr2)

1

In [88]:
np.max(arr2)

7

# Assignment practice

In [3]:
import numpy as np

In [6]:

list_ = [ '1' , '2','3','4','5' ]


In [7]:

array_list = np.array(object = list_)

In [8]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')