Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]


array_list = np.array(object = list_)

Ans : Well, the main difference between List and ArrayList is that List is an interface while ArrayList is a class. Most importantly, it implements the List interface, which also means that ArrayList is a subtype of the List interface.

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Ans : 

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data type of each element in list_
for elem in list_:
    print(type(elem))

# Print the data type of each element in array_list
for elem in np.nditer(array_list):
    print(type(elem.item()))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Ans - 

The statement `array_list = np.array(object=list_, dtype=int)` creates a NumPy array named array_list by converting a Python list list to a NumPy array of integers.

Here's a breakdown of the statement:

* np.array : This is a NumPy function that creates an array from a given object.
* object=list_ : This is the object that is converted to an array. In this case, list is a Python list.
* dtype=int : This specifies the data type of the elements in the array. In this case, the elements are converted to the integer data type.

So, the resulting array `array_list will have the same elements as the original list, but with each element converted to an integer. The variable name suggests that the resulting array is a list of integers.

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size



In [2]:
import numpy as np

# define a sample array
num_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# find the shape of the array
shape = num_array.shape
print("Shape of num_array:", shape)

# find the size of the array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (3, 3)
Size of num_array: 9


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [3]:
import numpy as np

array_zeros = np.zeros((3, 3))
print(array_zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [4]:
import numpy as np

# Create an identity matrix of shape (5,5)
identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
