In [1]:
# numpy me array and string ke sath khelte hain
import numpy as np

In [2]:
# list ko array me badalna
l = [1,2,3,4,5,6]

In [3]:
ar = np.array(l)

In [4]:
ar

array([1, 2, 3, 4, 5, 6])

In [5]:
type(l)

list

In [6]:
type(ar)

numpy.ndarray

In [7]:
# nd ka mtlb nd = (n dimensional)
l2 = [[1,2,3,4],[5,6,7,8]]

In [8]:
l2 

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [9]:
np.array(l2)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# one kostak mtlb one dimensional and two kostak mtlb two dimensional
# np.array function me list ko array me change kr sakte hain 
# np.asarray function  me bhi same
# np.asanyarray function me bhi list ko array me badal sakte hain
 
a = [1,2,4,5,6,9]

In [11]:
np.array(a)

array([1, 2, 4, 5, 6, 9])

In [12]:
np.asanyarray(a)

array([1, 2, 4, 5, 6, 9])

In [13]:
np.asarray(a)

array([1, 2, 4, 5, 6, 9])

In [14]:
# matrix subset of array hota hai 
# matrix always two dimentional hota hai
np.matrix(l)

matrix([[1, 2, 3, 4, 5, 6]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4, 5, 6])

In [17]:
# isse swallow copy bhi kahte hain
c =  a

In [18]:
c

array([1, 2, 3, 4, 5, 6])

In [19]:
# jb hamne a ko c variable me rakh diya to c me changes karne me a me changes apne aap ho jata hai

c[0]

1

In [20]:
# abhi c ka 0th variable 1 aaya hai

c[0] = 88

In [21]:
c[0]

88

In [22]:
a[0]

88

In [23]:
a

array([88,  2,  3,  4,  5,  6])

In [24]:
# isse deep copy bhi kahte hain
d = np.copy(a)

In [25]:
d

array([88,  2,  3,  4,  5,  6])

In [26]:
a[0] = 99

In [27]:
a

array([99,  2,  3,  4,  5,  6])

In [28]:
# deep copy me 
d

array([88,  2,  3,  4,  5,  6])

In [29]:
np.fromfunction(lambda i,j : i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
iterable = (i*i for i in range(5))

In [32]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
# String ko array me badalna

np.fromstring('326, 326' , sep= ',')

array([326., 326.])

In [34]:
 l = [1,2,3,4,5,6,6]

In [35]:
l

[1, 2, 3, 4, 5, 6, 6]

In [36]:
ar = np.array(l)

In [37]:
ar

array([1, 2, 3, 4, 5, 6, 6])

In [38]:
# ndim karne me output 1 aane ka mtlb one dimentional hota hai
ar.ndim

1

In [39]:
l2 = [[1,3,4,5,6,6] , [21,34,45,56,76,43]]

In [40]:
l2

[[1, 3, 4, 5, 6, 6], [21, 34, 45, 56, 76, 43]]

In [41]:
ar2 = np.array(l2)

In [42]:
ar2

array([[ 1,  3,  4,  5,  6,  6],
       [21, 34, 45, 56, 76, 43]])

In [43]:
# output 2 ka mtlb two dimentional
ar2.ndim

2

In [44]:
# kitne element available hain ushke liye

ar.size

7

In [45]:
ar2.size

12

In [46]:
ar.shape

(7,)

In [47]:
# ishka output 2,6 hai mtlb 2-row , 6-columns

ar2.shape

(2, 6)

In [ ]:
arr

In [ ]:
# Range hamesha integer leta hai 
# ishke andar data produce hota hai

range(5)

In [ ]:
list(range(9))

In [ ]:
# floating point ke liye arange function

np.arange(2.3,6.7)

In [ ]:
np.arange (2.3,6.7,2)

In [ ]:
list(np.arange (2.3,6.7,2))

In [52]:
# is function 2,5 ke beech me 3-3 ka different hoga 

np.linspace(2,5,3)

array([2. , 3.5, 5. ])

In [59]:
np.zeros(4)

array([0., 0., 0., 0.])

In [60]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
np.zeros((2,3,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [63]:
np.zeros((2,4,6,8))

array([[[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
     

In [64]:
on = np.ones(4)

In [65]:
on

array([1., 1., 1., 1.])

In [55]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [56]:
np.ones((3,4,7))

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [57]:
np.ones((2,4,6,8))

array([[[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.],
     

In [67]:
# upper wale variable me hm multiply , addition  bhi kr sakte hain 

on + 6

array([7., 7., 7., 7.])

In [68]:
on * 4

array([4., 4., 4., 4.])

In [69]:
# koi bhi opration ke sakte hain 

on + 9 - 4

array([6., 6., 6., 6.])

In [70]:
np.empty ((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [72]:
 np.empty((2,5,9))

array([[[1.01420545e-311, 6.95169507e-310, 1.01420834e-311,
         1.01421664e-311, 6.95169507e-310, 1.01420833e-311,
         6.95169507e-310, 1.01421661e-311, 1.01421661e-311],
        [1.01421147e-311, 1.01421147e-311, 1.01421147e-311,
         1.01421664e-311, 1.01421823e-311, 1.01420833e-311,
         1.01421664e-311, 1.01421146e-311, 1.01420833e-311],
        [1.01420833e-311, 1.01420833e-311, 1.01421691e-311,
         1.01421822e-311, 1.01420833e-311, 1.01420833e-311,
         1.01420833e-311, 6.95169507e-310, 1.01420833e-311],
        [1.01420833e-311, 1.01421691e-311, 1.01421691e-311,
         1.01420833e-311, 1.01421691e-311, 1.01420833e-311,
         1.01421691e-311, 1.01421691e-311, 1.01420833e-311],
        [1.01421691e-311, 1.01421691e-311, 1.01421691e-311,
         1.01420833e-311, 1.01421822e-311, 6.95169507e-310,
         1.01421147e-311, 6.95169507e-310, 1.01421661e-311]],

       [[1.01421661e-311, 1.01421146e-311, 1.01421822e-311,
         6.95169507e-310, 1.01421

In [73]:
# asrhetic matrixes

np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [75]:
# logspace bhi linspace ki tarah kaam karta hai data produce karne ka

np.logspace(3,7)

array([1.00000000e+03, 1.20679264e+03, 1.45634848e+03, 1.75751062e+03,
       2.12095089e+03, 2.55954792e+03, 3.08884360e+03, 3.72759372e+03,
       4.49843267e+03, 5.42867544e+03, 6.55128557e+03, 7.90604321e+03,
       9.54095476e+03, 1.15139540e+04, 1.38949549e+04, 1.67683294e+04,
       2.02358965e+04, 2.44205309e+04, 2.94705170e+04, 3.55648031e+04,
       4.29193426e+04, 5.17947468e+04, 6.25055193e+04, 7.54312006e+04,
       9.10298178e+04, 1.09854114e+05, 1.32571137e+05, 1.59985872e+05,
       1.93069773e+05, 2.32995181e+05, 2.81176870e+05, 3.39322177e+05,
       4.09491506e+05, 4.94171336e+05, 5.96362332e+05, 7.19685673e+05,
       8.68511374e+05, 1.04811313e+06, 1.26485522e+06, 1.52641797e+06,
       1.84206997e+06, 2.22299648e+06, 2.68269580e+06, 3.23745754e+06,
       3.90693994e+06, 4.71486636e+06, 5.68986603e+06, 6.86648845e+06,
       8.28642773e+06, 1.00000000e+07])

In [77]:
arrr = np.random.randn(3,6)

In [78]:
arrr

array([[ 0.82883794, -1.04608676, -0.4150974 ,  1.19081811,  1.24116022,
        -0.03102468],
       [-0.51017527, -1.4267813 , -1.51395624,  0.50035752,  1.27856765,
         0.60625913],
       [-1.28160432, -1.02508156,  0.5504815 ,  0.71440501,  2.41788346,
         0.13430608]])

In [82]:
import pandas as pd

In [83]:
pd.DataFrame(arrr)

0         1         2         3         4         5
0  0.828838 -1.046087 -0.415097  1.190818  1.241160 -0.031025
1 -0.510175 -1.426781 -1.513956  0.500358  1.278568  0.606259
2 -1.281604 -1.025082  0.550481  0.714405  2.417883  0.134306

In [87]:
np.random.randint(2,65 , (345,556))

array([[59, 21, 44, ..., 62,  2, 13],
       [23, 43, 30, ..., 43,  8, 18],
       [18,  3, 39, ..., 54, 57,  9],
       ...,
       [19,  9, 16, ..., 46, 47, 52],
       [38, 10, 51, ..., 42, 41, 40],
       [16, 32, 35, ..., 46,  5, 53]])

In [89]:
arrr2 = np.random.randint(2,65 , (345,556))

In [90]:
arrr2

array([[36, 27, 24, ..., 49,  8, 18],
       [18, 25, 30, ..., 56, 48,  7],
       [23, 34, 51, ..., 39,  8, 37],
       ...,
       [20, 53, 16, ..., 59, 34, 24],
       [17,  5, 50, ...,  7,  3, 46],
       [44, 20, 14, ..., 11,  4, 43]])

In [91]:
pd.DataFrame(arrr2)

0    1    2    3    4    5    6    7    8    9    ...  546  547  548  \
0     36   27   24   42    6   32    4   25   49   17  ...   31   47   16   
1     18   25   30   42   45   39    3   25   64   54  ...    6   37    6   
2     23   34   51   34   36   50   17   59   58   61  ...   46   44   19   
3     17   37   58   44   54   18   50   12   52   40  ...    6   51    5   
4     19   15   20   26   17   49   56   39   17   16  ...    9   56    7   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
340   60   58   43   18   11   39   19   21   47   43  ...   19   47   15   
341   50   18   38   27    2   47   20    4   47   54  ...   39   10   43   
342   20   53   16   49   54    8   45   29   44   29  ...   48   21   43   
343   17    5   50   62   53   51   50   14   17   57  ...   57    5   42   
344   44   20   14   43   34   10   24   22   42   43  ...   50   39    8   

     549  550  551  552  553  554  555  
0     64    5   39   29   49    8   18  
1     44   25   36   15   56   48    7  
2     60   49   43   37   39    8   37  
3     37    5   49   36   25   35   12  
4     58   12   34    3   14   20   42  
..   ...  ...  ...  ...  ...  ...  ...  
340    9   58   63   35   29   25   58  
341   48   37   30   53   58   13   42  
342   54   64   43   12   59   34   24  
343   25   52   22   62    7    3   46  
344   12   17   48   11   11    4   43  

[345 rows x 556 columns]

In [92]:
pd.DataFrame(arrr2).to_csv('test.csv')

In [95]:
# jitna hamare passs data hai usi ko shape change kr sakte hain jaise ishka output me aisa mtlb column 6 aur row 3 hai mtlb total 18 data save hain 

arrr4 = np.random.rand(3,6)

In [94]:
arrr4

array([[0.03291935, 0.41425246, 0.34846847, 0.22926871, 0.71619365,
        0.98164176],
       [0.78137301, 0.5095435 , 0.81215055, 0.31041727, 0.21112445,
        0.92707882],
       [0.83905222, 0.18087186, 0.14339541, 0.10803452, 0.31651878,
        0.21120447]])

In [99]:
# ab isi 18 data me row aur column ki shape change kr sakte hain

arrr4.reshape(9,2)

array([[0.79076894, 0.61312279],
       [0.21276253, 0.86833617],
       [0.06434461, 0.48392107],
       [0.10202004, 0.49606196],
       [0.72529851, 0.38045224],
       [0.98260727, 0.79161285],
       [0.63387506, 0.31512081],
       [0.35324033, 0.19385909],
       [0.49432456, 0.46500563]])