In [1]:
import numpy as np

### sort , search and counting function

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,46,34,23,5,34,656,534,432,])

In [4]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  46,  34,  23,   5,
        34, 656, 534, 432])

In [6]:
# sort mtlb asccending order

np.sort(arr)

array([  1,   2,   3,   4,   5,   5,   6,   7,   8,   9,  23,  34,  34,
        46, 432, 534, 656])

In [8]:
# searchsorted me jo bhi no. hm pass karenge usse kahan pe rakhna hai output me pta chalta hai

np.searchsorted(arr , 76)

14

In [9]:
arr1 = ([1,43,54,56,67,0,0,67,0,0,70,70])

In [10]:
arr1

[1, 43, 54, 56, 67, 0, 0, 67, 0, 0, 70, 70]

In [11]:
np.nonzero(arr1)

(array([ 0,  1,  2,  3,  4,  7, 10, 11], dtype=int64),)

In [12]:
np.count_nonzero(arr1)

8

In [13]:
np.where(arr > 9)

(array([ 9, 10, 11, 13, 14, 15, 16], dtype=int64),)

In [14]:
np.extract(arr > 9 , arr)

array([ 46,  34,  23,  34, 656, 534, 432])

### Byte swapping


In [15]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  46,  34,  23,   5,
        34, 656, 534, 432])

In [16]:
arr.byteswap()

array([   16777216,    33554432,    50331648,    67108864,    83886080,
         100663296,   117440512,   134217728,   150994944,   771751936,
         570425344,   385875968,    83886080,   570425344, -1878917120,
         369229824, -1342111744])

In [17]:
import numpy.matlib as nm

In [18]:
nm.zeros(7)

matrix([[0., 0., 0., 0., 0., 0., 0.]])

In [21]:
nm.ones((3,9))

matrix([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
nm.eye(6)

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

### Linear  Algebra 

In [24]:
arr1 = np.random.randint([[1,3,3,4,5] ,[3,5,6,7,9]])

In [30]:
arr2 = np.random.randint([[4,5,6,5,7],[6,7,7,4,6]])

In [31]:
arr1

array([[0, 1, 0, 1, 0],
       [2, 2, 0, 1, 6]])

In [32]:
arr2

array([[3, 3, 4, 2, 4],
       [0, 2, 2, 1, 0]])